/* soapClient.cpp
   Generated by gSOAP 2.8.22 from calc.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "stdafx.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.22 2015-06-26 01:37:45 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___JR1__Add(struct soap *soap, const char *soap_endpoint, const char *soap_action, _JR3__Add *JR3__Add, _JR3__AddResponse &JR3__AddResponse)
{	struct __JR1__Add soap_tmp___JR1__Add;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.1.104:15618/calcservice";
	if (soap_action == NULL)
		soap_action = "http://o2.jrrpc.com/ICalc/Add";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___JR1__Add.JR3__Add = JR3__Add;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___JR1__Add(soap, &soap_tmp___JR1__Add);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___JR1__Add(soap, &soap_tmp___JR1__Add, "-JR1:Add", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___JR1__Add(soap, &soap_tmp___JR1__Add, "-JR1:Add", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&JR3__AddResponse)
		return soap_closesock(soap);
	JR3__AddResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	JR3__AddResponse.soap_get(soap, "JR3:AddResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
