/* soapStub.h
   Generated by gSOAP 2.8.22 from WeatherWeb.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_Weather1	"http://WebXml.com.cn/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20822
# error "GSOAP VERSION 20822 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_Weather1__ArrayOfString
#define SOAP_TYPE_Weather1__ArrayOfString (8)
/* Weather1:ArrayOfString */
class SOAP_CMAC Weather1__ArrayOfString
{
public:
	int __sizestring;	/* sequence of elements <string> */
	char **string;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique type id SOAP_TYPE_Weather1__ArrayOfString */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         Weather1__ArrayOfString() { Weather1__ArrayOfString::soap_default(NULL); }
	virtual ~Weather1__ArrayOfString() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportCity
#define SOAP_TYPE__Weather1__getSupportCity (9)
/* Weather1:getSupportCity */
class SOAP_CMAC _Weather1__getSupportCity
{
public:
	char *byProvinceName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique type id SOAP_TYPE__Weather1__getSupportCity */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportCity() { _Weather1__getSupportCity::soap_default(NULL); }
	virtual ~_Weather1__getSupportCity() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportCityResponse
#define SOAP_TYPE__Weather1__getSupportCityResponse (10)
/* Weather1:getSupportCityResponse */
class SOAP_CMAC _Weather1__getSupportCityResponse
{
public:
	Weather1__ArrayOfString *getSupportCityResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type Weather1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique type id SOAP_TYPE__Weather1__getSupportCityResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportCityResponse() { _Weather1__getSupportCityResponse::soap_default(NULL); }
	virtual ~_Weather1__getSupportCityResponse() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportProvince
#define SOAP_TYPE__Weather1__getSupportProvince (11)
/* Weather1:getSupportProvince */
class SOAP_CMAC _Weather1__getSupportProvince
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique type id SOAP_TYPE__Weather1__getSupportProvince */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportProvince() { _Weather1__getSupportProvince::soap_default(NULL); }
	virtual ~_Weather1__getSupportProvince() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportProvinceResponse
#define SOAP_TYPE__Weather1__getSupportProvinceResponse (12)
/* Weather1:getSupportProvinceResponse */
class SOAP_CMAC _Weather1__getSupportProvinceResponse
{
public:
	Weather1__ArrayOfString *getSupportProvinceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type Weather1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique type id SOAP_TYPE__Weather1__getSupportProvinceResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportProvinceResponse() { _Weather1__getSupportProvinceResponse::soap_default(NULL); }
	virtual ~_Weather1__getSupportProvinceResponse() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportDataSet
#define SOAP_TYPE__Weather1__getSupportDataSet (13)
/* Weather1:getSupportDataSet */
class SOAP_CMAC _Weather1__getSupportDataSet
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique type id SOAP_TYPE__Weather1__getSupportDataSet */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportDataSet() { _Weather1__getSupportDataSet::soap_default(NULL); }
	virtual ~_Weather1__getSupportDataSet() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportDataSetResponse_getSupportDataSetResult
#define SOAP_TYPE__Weather1__getSupportDataSetResponse_getSupportDataSetResult (23)
/* Weather1:getSupportDataSetResponse-getSupportDataSetResult */
class SOAP_CMAC _Weather1__getSupportDataSetResponse_getSupportDataSetResult
{
public:
	char *xsd__schema;	/* required element of type xsd:schema */
	char *__any;
public:
	virtual int soap_type() const { return 23; } /* = unique type id SOAP_TYPE__Weather1__getSupportDataSetResponse_getSupportDataSetResult */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportDataSetResponse_getSupportDataSetResult() { _Weather1__getSupportDataSetResponse_getSupportDataSetResult::soap_default(NULL); }
	virtual ~_Weather1__getSupportDataSetResponse_getSupportDataSetResult() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getSupportDataSetResponse
#define SOAP_TYPE__Weather1__getSupportDataSetResponse (14)
/* Weather1:getSupportDataSetResponse */
class SOAP_CMAC _Weather1__getSupportDataSetResponse
{
public:
	_Weather1__getSupportDataSetResponse_getSupportDataSetResult *getSupportDataSetResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type Weather1:getSupportDataSetResponse-getSupportDataSetResult */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique type id SOAP_TYPE__Weather1__getSupportDataSetResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getSupportDataSetResponse() { _Weather1__getSupportDataSetResponse::soap_default(NULL); }
	virtual ~_Weather1__getSupportDataSetResponse() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getWeatherbyCityName
#define SOAP_TYPE__Weather1__getWeatherbyCityName (15)
/* Weather1:getWeatherbyCityName */
class SOAP_CMAC _Weather1__getWeatherbyCityName
{
public:
	char *theCityName;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique type id SOAP_TYPE__Weather1__getWeatherbyCityName */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getWeatherbyCityName() { _Weather1__getWeatherbyCityName::soap_default(NULL); }
	virtual ~_Weather1__getWeatherbyCityName() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getWeatherbyCityNameResponse
#define SOAP_TYPE__Weather1__getWeatherbyCityNameResponse (16)
/* Weather1:getWeatherbyCityNameResponse */
class SOAP_CMAC _Weather1__getWeatherbyCityNameResponse
{
public:
	Weather1__ArrayOfString *getWeatherbyCityNameResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type Weather1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 16; } /* = unique type id SOAP_TYPE__Weather1__getWeatherbyCityNameResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getWeatherbyCityNameResponse() { _Weather1__getWeatherbyCityNameResponse::soap_default(NULL); }
	virtual ~_Weather1__getWeatherbyCityNameResponse() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getWeatherbyCityNamePro
#define SOAP_TYPE__Weather1__getWeatherbyCityNamePro (17)
/* Weather1:getWeatherbyCityNamePro */
class SOAP_CMAC _Weather1__getWeatherbyCityNamePro
{
public:
	char *theCityName;	/* optional element of type xsd:string */
	char *theUserID;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 17; } /* = unique type id SOAP_TYPE__Weather1__getWeatherbyCityNamePro */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getWeatherbyCityNamePro() { _Weather1__getWeatherbyCityNamePro::soap_default(NULL); }
	virtual ~_Weather1__getWeatherbyCityNamePro() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__getWeatherbyCityNameProResponse
#define SOAP_TYPE__Weather1__getWeatherbyCityNameProResponse (18)
/* Weather1:getWeatherbyCityNameProResponse */
class SOAP_CMAC _Weather1__getWeatherbyCityNameProResponse
{
public:
	Weather1__ArrayOfString *getWeatherbyCityNameProResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type Weather1:ArrayOfString */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 18; } /* = unique type id SOAP_TYPE__Weather1__getWeatherbyCityNameProResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__getWeatherbyCityNameProResponse() { _Weather1__getWeatherbyCityNameProResponse::soap_default(NULL); }
	virtual ~_Weather1__getWeatherbyCityNameProResponse() { }
};
#endif

#ifndef SOAP_TYPE__Weather1__DataSet
#define SOAP_TYPE__Weather1__DataSet (19)
/* Weather1:DataSet */
class SOAP_CMAC _Weather1__DataSet
{
public:
	char *xsd__schema;	/* required element of type xsd:schema */
	char *__any;
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 19; } /* = unique type id SOAP_TYPE__Weather1__DataSet */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _Weather1__DataSet() { _Weather1__DataSet::soap_default(NULL); }
	virtual ~_Weather1__DataSet() { }
};
#endif

#ifndef SOAP_TYPE___Weather1__getSupportCity
#define SOAP_TYPE___Weather1__getSupportCity (28)
/* Operation wrapper: */
struct __Weather1__getSupportCity
{
public:
	_Weather1__getSupportCity *Weather1__getSupportCity;	/* optional element of type Weather1:getSupportCity */
public:
	int soap_type() const { return 28; } /* = unique type id SOAP_TYPE___Weather1__getSupportCity */
};
#endif

#ifndef SOAP_TYPE___Weather1__getSupportProvince
#define SOAP_TYPE___Weather1__getSupportProvince (32)
/* Operation wrapper: */
struct __Weather1__getSupportProvince
{
public:
	_Weather1__getSupportProvince *Weather1__getSupportProvince;	/* optional element of type Weather1:getSupportProvince */
public:
	int soap_type() const { return 32; } /* = unique type id SOAP_TYPE___Weather1__getSupportProvince */
};
#endif

#ifndef SOAP_TYPE___Weather1__getSupportDataSet
#define SOAP_TYPE___Weather1__getSupportDataSet (36)
/* Operation wrapper: */
struct __Weather1__getSupportDataSet
{
public:
	_Weather1__getSupportDataSet *Weather1__getSupportDataSet;	/* optional element of type Weather1:getSupportDataSet */
public:
	int soap_type() const { return 36; } /* = unique type id SOAP_TYPE___Weather1__getSupportDataSet */
};
#endif

#ifndef SOAP_TYPE___Weather1__getWeatherbyCityName
#define SOAP_TYPE___Weather1__getWeatherbyCityName (40)
/* Operation wrapper: */
struct __Weather1__getWeatherbyCityName
{
public:
	_Weather1__getWeatherbyCityName *Weather1__getWeatherbyCityName;	/* optional element of type Weather1:getWeatherbyCityName */
public:
	int soap_type() const { return 40; } /* = unique type id SOAP_TYPE___Weather1__getWeatherbyCityName */
};
#endif

#ifndef SOAP_TYPE___Weather1__getWeatherbyCityNamePro
#define SOAP_TYPE___Weather1__getWeatherbyCityNamePro (44)
/* Operation wrapper: */
struct __Weather1__getWeatherbyCityNamePro
{
public:
	_Weather1__getWeatherbyCityNamePro *Weather1__getWeatherbyCityNamePro;	/* optional element of type Weather1:getWeatherbyCityNamePro */
public:
	int soap_type() const { return 44; } /* = unique type id SOAP_TYPE___Weather1__getWeatherbyCityNamePro */
};
#endif

#ifndef SOAP_TYPE___Weather1__getSupportCity_
#define SOAP_TYPE___Weather1__getSupportCity_ (46)
/* Operation wrapper: */
struct __Weather1__getSupportCity_
{
public:
	_Weather1__getSupportCity *Weather1__getSupportCity;	/* optional element of type Weather1:getSupportCity */
public:
	int soap_type() const { return 46; } /* = unique type id SOAP_TYPE___Weather1__getSupportCity_ */
};
#endif

#ifndef SOAP_TYPE___Weather1__getSupportProvince_
#define SOAP_TYPE___Weather1__getSupportProvince_ (48)
/* Operation wrapper: */
struct __Weather1__getSupportProvince_
{
public:
	_Weather1__getSupportProvince *Weather1__getSupportProvince;	/* optional element of type Weather1:getSupportProvince */
public:
	int soap_type() const { return 48; } /* = unique type id SOAP_TYPE___Weather1__getSupportProvince_ */
};
#endif

#ifndef SOAP_TYPE___Weather1__getSupportDataSet_
#define SOAP_TYPE___Weather1__getSupportDataSet_ (50)
/* Operation wrapper: */
struct __Weather1__getSupportDataSet_
{
public:
	_Weather1__getSupportDataSet *Weather1__getSupportDataSet;	/* optional element of type Weather1:getSupportDataSet */
public:
	int soap_type() const { return 50; } /* = unique type id SOAP_TYPE___Weather1__getSupportDataSet_ */
};
#endif

#ifndef SOAP_TYPE___Weather1__getWeatherbyCityName_
#define SOAP_TYPE___Weather1__getWeatherbyCityName_ (52)
/* Operation wrapper: */
struct __Weather1__getWeatherbyCityName_
{
public:
	_Weather1__getWeatherbyCityName *Weather1__getWeatherbyCityName;	/* optional element of type Weather1:getWeatherbyCityName */
public:
	int soap_type() const { return 52; } /* = unique type id SOAP_TYPE___Weather1__getWeatherbyCityName_ */
};
#endif

#ifndef SOAP_TYPE___Weather1__getWeatherbyCityNamePro_
#define SOAP_TYPE___Weather1__getWeatherbyCityNamePro_ (54)
/* Operation wrapper: */
struct __Weather1__getWeatherbyCityNamePro_
{
public:
	_Weather1__getWeatherbyCityNamePro *Weather1__getWeatherbyCityNamePro;	/* optional element of type Weather1:getWeatherbyCityNamePro */
public:
	int soap_type() const { return 54; } /* = unique type id SOAP_TYPE___Weather1__getWeatherbyCityNamePro_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (55)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 55; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (56)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 56; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (58)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 58; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (61)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 61; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (62)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 62; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__xsd__schema
#define SOAP_TYPE__xsd__schema (7)
typedef char *_xsd__schema;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getSupportCity(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getSupportCity *Weather1__getSupportCity, _Weather1__getSupportCityResponse &Weather1__getSupportCityResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getSupportProvince(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getSupportProvince *Weather1__getSupportProvince, _Weather1__getSupportProvinceResponse &Weather1__getSupportProvinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getSupportDataSet(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getSupportDataSet *Weather1__getSupportDataSet, _Weather1__getSupportDataSetResponse &Weather1__getSupportDataSetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getWeatherbyCityName(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getWeatherbyCityName *Weather1__getWeatherbyCityName, _Weather1__getWeatherbyCityNameResponse &Weather1__getWeatherbyCityNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getWeatherbyCityNamePro(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getWeatherbyCityNamePro *Weather1__getWeatherbyCityNamePro, _Weather1__getWeatherbyCityNameProResponse &Weather1__getWeatherbyCityNameProResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getSupportCity_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getSupportCity *Weather1__getSupportCity, _Weather1__getSupportCityResponse &Weather1__getSupportCityResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getSupportProvince_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getSupportProvince *Weather1__getSupportProvince, _Weather1__getSupportProvinceResponse &Weather1__getSupportProvinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getSupportDataSet_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getSupportDataSet *Weather1__getSupportDataSet, _Weather1__getSupportDataSetResponse &Weather1__getSupportDataSetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getWeatherbyCityName_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getWeatherbyCityName *Weather1__getWeatherbyCityName, _Weather1__getWeatherbyCityNameResponse &Weather1__getWeatherbyCityNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___Weather1__getWeatherbyCityNamePro_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _Weather1__getWeatherbyCityNamePro *Weather1__getWeatherbyCityNamePro, _Weather1__getWeatherbyCityNameProResponse &Weather1__getWeatherbyCityNameProResponse);

#endif

/* End of soapStub.h */
